services:
  rtems-dev:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: rtems-dev
    userns_mode: "keep-id"
    user: "thomas"
    volumes:
      - /home/thomas/Projects/MCU-exp/workspace:/home/thomas/workspace:z,U
    stdin_open: true
    tty: true

  renode:
    build:
      context: .
      dockerfile: Dockerfile.renode
    container_name: renode-emu
    userns_mode: "keep-id"
    user: "thomas"
    ports:
      - "1024:1024" # Monitor port
      - "1234:1234" # GDB port
    volumes:
      - /home/thomas/Projects/MCU-exp/workspace:/home/thomas/workspace:z,U
    stdin_open: true
    tty: true
