services:
  rtems-dev:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: rtems-dev
    user: thomas
    volumes:
      # Syncs your local project folder to the container
      # - .:/home/thomas/project
<<<<<<< HEAD
      
=======

>>>>>>> 5e681c0c96bade3fe62adf88d9a090a71ade402c
      # Persists the workspace
      - /home/thomas/Projects/MCU-exp/workspace:/home/thomas/workspace:z,U
      
    # Keeps the container running so you can exec into it
    stdin_open: true
    tty: true
